### ISSUE TITLE
Issue in sum_even_fibonacci.py

### ISSUE THREAD

**Issue by ThomasBeucler** [ThomasBeucler/Team1-VERSO-Activity#9]
**Description**
A clear and concise description of what the issue/bug is.

The variable 'b' does not update properly within the while loop of the program. This results in the program being caught in an infinite loop.

**Steps to Reproduce**
1. First step to reproduce the issue/bug

Run the program.

3. Second step to reproduce the issue/bug
4. Third step to reproduce the issue/bug

**Expected Behavior**

The program should print the proper answer for the sum of all fibonacci numbers below 4,000,000, which should be 4613732.

**Actual Behavior**
A clear and concise description of what actually happened.

The program runs in an infinite loop.

**Screenshots**
If applicable, add screenshots to help explain the issue/bug.

**Additional Information**
* Operating System: Windows 11, 64 bit
* Browser: Chrome
* Version: 123.0.6312.60 
* Any other relevant information: Using PyCharm with python 3.12

**Possible Solution**
If you have any suggestions for a possible solution, please include them here.

Make sure that the loop iterates properly.

**Related Issues**
Are there any related issues? If so, please link to them here.

**Priority**
How critical is this issue/bug? Low, medium, or high priority?

This is a high priority issue. The program will not complete without it being fixed

**Reproducibility**
How often can this issue/bug be reproduced? Always, sometimes, or random?

This bug happens every time

**Impact**
What is the impact of this issue/bug? Low, medium, or high?

The impact of this bug is high

**Comment by nbortz** [comment]
Uneeded semicolon after line 3, changed <= for while loop to <, changed the / for division to %, changed a, b = b, b to a, b = b, a+b. Program now works as it should, gives the correct answer
